export const QUOTESTORE = [
    {'Morty': 'Nobody exists on purpose. Nobody belongs anywhere. We\'re all going to die. Come watch TV.'},
    {'Morty': 'Gaslighting does not exist, you made it up because you are f****** crazy.'},
    {'Morty': 'You\'re a monster. You\'re like Hitler but even Hitler cared about Germany or something!'},
    {'Rick': 'Weddings are basically funerals with cake.'},
    {'Rick': 'I turned myself into a pickle. I\'m Pickle Riiiiick.'},
    {'Rick': 'I\'m sorry, but your opinion means very little to me.'},
    {'Rick': 'Hey, muchacho, does your planet have wiper fluid yet or you gonna freak out and start worshipping us?'},
    {'Rick': 'Wubba lubba dub dub!'},
    {'Rick': 'Listen, I\'m not the nicest guy in the universe, because I\'m the smartest, and being nice is something stupid people do to hedge their bets.'},
    {'Rick': 'What about the reality where Hitler cured cancer? Just don\'t think about it, Morty.'},
    {'Rick': 'We\'ve got a lot of friends and family to exterminate.'},
    {'Rick': 'Sometimes science is more art than science, Morty. Lot of people don’t get that.'},
    {'Jerry': 'Life is effort. I\'ll stop when I die!'},
    {'Summer': 'If I die, don\'t eat my ass. That\'d be weird.'},
    {'Summer': 'You don\'t love people in hopes of a reward, Dad. You love them unconditionally.'},
    {'Mr. Needful': 'I just want to go back to hell, where everyone thinks I\'m smart and funny.'},
];